language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
install: true
before_script:
  - composer install
  - composer require atoum/atoum
script:
  - wget https://phar.phpunit.de/phpunit.phar
  - php phpunit.phar --version
  - php phpunit.phar test/terbilangTest.php
