language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
install: true
script:
  - phpunit --version
  - wget https://phar.phpunit.de/phpunit.phar
  - php phpunit.phar --version
  - phpunit test/terbilangTest.php
  - php phpunit.phar test/terbilangTest.php
